### PR TITLE
Ensure Observables catch errors when requesting data

### PR DESCRIPTION
**Pull request by rozza**
JAVA-2048

### CODE REVIEW

**Comment by rozza** [comment]
Good catch - I added the where clause as an after thought and as the test passed didnt think anything of it.  Will review.

**Comment by rozza** [comment]
Simplified the test and will open a new ticket about the bug.

**Comment by rozza** [comment]
Turns out its only bad tests - rather than broken behaviour in the Observables.  Have fixed the tests so they test what they intended to.

**Comment by jyemin** [comment]
lgtm

**Pull request closed without merging**
