### PR TITLE
Installation guide

### PR DESCRIPTION
**Pull request by rozza**
JAVA-1718

[Review on Reviewable](https://reviewable.io/reviews/rozza/mongo-java-driver/79)

### CODE REVIEW

**Comment by rozza** [comment]
http://rosslawley.co.uk/mongo-java-driver/3.0/tutorial/installation-guide/

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/79)



---

I like it.  See if you can add a bson jar as well.  This will require a bit of a change to the language at the top, I realize.

---

<sup>**[docs/reference/content/tutorial/installation-guide.md, line 39 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/79#-JlQi3-uL0l7-i2cORu_)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/2b684140b0ae835f3c296d6cd2cb792b1c52e08d/docs/reference/content/tutorial/installation-guide.md#L39)):</sup>
Did you consider adding one for bson as well?  I think we should.

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/79)







---

<sup>**[docs/reference/content/tutorial/installation-guide.md, line 39 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/79#-JlQi3-uL0l7-i2cORu_)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/2b684140b0ae835f3c296d6cd2cb792b1c52e08d/docs/reference/content/tutorial/installation-guide.md#L39)):</sup>
Done.

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/79)







---

<sup>**[docs/reference/content/tutorial/installation-guide.md, line 12 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/79#-JlQoFobAZ4w2dbwYJ5j)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/0dbb3839a6e70e453c509bbbe497abb2f08ddd98/docs/reference/content/tutorial/installation-guide.md#L12)):</sup>
all caps on Bson

---

<sup>**[docs/reference/content/tutorial/installation-guide.md, line 36 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/79#-JlQoZ0-no6yAvR8ilsR)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/0dbb3839a6e70e453c509bbbe497abb2f08ddd98/docs/reference/content/tutorial/installation-guide.md#L36)):</sup>
All caps

---

<sup>**[docs/reference/content/tutorial/installation-guide.md, line 38 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/79#-JlQobJ7jWJNX1Os-UhS)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/0dbb3839a6e70e453c509bbbe497abb2f08ddd98/docs/reference/content/tutorial/installation-guide.md#L38)):</sup>
This library comprehensively supports.... (so that you don't have to repeat BSON

---

**Comment by rozza** [comment]
rebased and merged

**Pull request closed without merging**
