### PR TITLE
First draft of a landing page

### PR DESCRIPTION
**Pull request by rozza**
JAVA-1695

[Review on Reviewable](https://reviewable.io/reviews/rozza/mongo-java-driver/77)

### CODE REVIEW

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/77)



---

I'm just going to reply here, since it's easier than finding what file a snippet comes from:

1. synchronus and asynchronus =>  synchronous and asynchronous
2. non blocking io  => non-block IO
3. MongoDB Java Driver  => MongoDB Driver
4. Move "Core Driver" to the end.  And say something like "The MongoDB Driver and Async Driver are both built on top of a new core library, which anyone can use to build alternative or experimental high-level APIs.
5. We're going to need more copies of that widget.  At a minimum, one for mongodb-driver-async.  And I think we should say that for new 3.0-based projects we should recommend mongodb-driver

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/77)



---

Oh, and get my picture out of there!

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/77)



---

Just noticed that there is no .nojeckyll file in public when I build. Not sure if that's a problem.

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/77)



---

Looking more at the top of the page:

I'd prefer that we kill the three bullets, remove the Quick Start link (makes me think i'm going to another page), and shrink the whole thing vertically.  It's just too much grey!

---

**Comment by rozza** [comment]
Done - and ready for review

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/77)



---

A thing of beauty.  Ship it!

---

**Comment by rozza** [comment]
rebased

**Pull request closed without merging**
