### PR TITLE
Added primer examples

### PR DESCRIPTION
**Pull request by rozza**
WRITING-1173

[Review on Reviewable](https://reviewable.io/reviews/rozza/mongo-java-driver/69)

### CODE REVIEW

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[driver-async/src/examples/primer/AggregatePrimer.java, line 34 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk39CXL7Z8blq5w0WqW)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver-async/src/examples/primer/AggregatePrimer.java#L34)):</sup>
Method names should start with a lower-case letter

---

<sup>**[driver-async/src/examples/primer/AggregatePrimer.java, line 34 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk39DPHv6yBw_o6rTMz)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver-async/src/examples/primer/AggregatePrimer.java#L34)):</sup>
What throws InterruptedException?

---

<sup>**[driver/build.gradle, line 24 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk37GgYTg6lTW7r0OcQ)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/build.gradle#L24)):</sup>
I haven't done this before in Gradle, but in regular Groovy/Java this would have to be +=.

---

<sup>**[driver/src/examples/primer/InsertPrimer.java, line 43 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk38Dp3PG41Y6_Ymp2r)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/src/examples/primer/InsertPrimer.java#L43)):</sup>
I know it's shorter the way you did it here, but it might line up better if you use the no-args constructor and append even for the first key/value pair

---

<sup>**[driver/src/examples/primer/RemovePrimer.java, line 25 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk38x2f3tS_h_NHk-le)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/src/examples/primer/RemovePrimer.java#L25)):</sup>
Change "Remove" to "Delete"

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[driver/src/examples/primer/AggregatePrimer.java, line 86 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk3BG-14Gxjk_MDqnR7)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/src/examples/primer/AggregatePrimer.java#L86)):</sup>
The double curly brace is might ugly.  We could fix the toString method of document, but it would be nicer to show this as JSON.  I noticed this when doing M101J, so for my lectures I delegate to a printJson method: 

 public static void printJson(Document document) {
        JsonWriter jsonWriter = new JsonWriter(new StringWriter(),
                                               new JsonWriterSettings(JsonMode.SHELL, false));
        new DocumentCodec().encode(jsonWriter, document,
                                   EncoderContext.builder()
                                                 .isEncodingCollectibleDocument(true)
                                                 .build());
        System.out.println(jsonWriter.getWriter());
        // System.out.println();
        System.out.flush();
    }

Not sure how to integrate that in to the primer though...

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[driver-async/src/examples/primer/AggregatePrimer.java, line 34 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk39DPHv6yBw_o6rTMz)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver-async/src/examples/primer/AggregatePrimer.java#L34)):</sup>
Done.

---

<sup>**[driver-async/src/examples/primer/AggregatePrimer.java, line 34 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk39CXL7Z8blq5w0WqW)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver-async/src/examples/primer/AggregatePrimer.java#L34)):</sup>
Done.

---

<sup>**[driver/build.gradle, line 24 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk37GgYTg6lTW7r0OcQ)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/build.gradle#L24)):</sup>
Done.

---

<sup>**[driver/src/examples/primer/RemovePrimer.java, line 25 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk38x2f3tS_h_NHk-le)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/src/examples/primer/RemovePrimer.java#L25)):</sup>
It correlates the to `examples-remove.yaml` So I'd prefer to keep  that mapping, even though the method used is delete

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[driver-async/src/examples/primer/AggregatePrimer.java, line 34 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk39DPHv6yBw_o6rTMz)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver-async/src/examples/primer/AggregatePrimer.java#L34)):</sup>
What's the answer?  I don't see that you removed them.

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[driver/src/examples/primer/InsertPrimer.java, line 43 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk38Dp3PG41Y6_Ymp2r)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/src/examples/primer/InsertPrimer.java#L43)):</sup>
Done.

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[driver-async/src/examples/primer/AggregatePrimer.java, line 34 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk39DPHv6yBw_o6rTMz)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver-async/src/examples/primer/AggregatePrimer.java#L34)):</sup>
Previously, I had used a latch in the callback - have removed and pushed

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[driver/src/examples/primer/AggregatePrimer.java, line 86 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk3BG-14Gxjk_MDqnR7)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/src/examples/primer/AggregatePrimer.java#L86)):</sup>
I can't see how we'd add that, we could just fix our string representation, to something nicer or I noticed that BsonDocument has a `toJson` method I could port that to Document and use that?

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[driver/src/examples/primer/AggregatePrimer.java, line 86 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk3BG-14Gxjk_MDqnR7)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/src/examples/primer/AggregatePrimer.java#L86)):</sup>
We could add a toJson() method to Document that does what this printJson method does.  The problem is that it can throw runtime exceptions if you're using values that are not encodable with the default DocumentCodec.  It will work fine if you stick to the supported value types, but it's not safe in the general case, which is why we haven't added anything like it to Document.

---

<sup>**[driver/src/examples/primer/RemovePrimer.java, line 25 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk38x2f3tS_h_NHk-le)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/src/examples/primer/RemovePrimer.java#L25)):</sup>
Weird, but ok.  

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[driver/src/examples/primer/AggregatePrimer.java, line 86 \[r1\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk3BG-14Gxjk_MDqnR7)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/c83d5e1b38dee31eafb793ab9ef8bc2462ab9479/driver/src/examples/primer/AggregatePrimer.java#L86)):</sup>
I've added two toJson() methods one that takes a custom DocumentCodec - if you like it we can keep it.

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)

Reviewed files:
- driver-async/build.gradle @ r1
- driver-async/src/examples/primer/AggregatePrimer.java @ r4
- driver-async/src/examples/primer/IndexesPrimer.java @ r2
- driver-async/src/examples/primer/InsertPrimer.java @ r3
- driver-async/src/examples/primer/PrimerTestCase.java @ r1
- driver-async/src/examples/primer/QueryPrimer.java @ r2
- driver-async/src/examples/primer/RemovePrimer.java @ r2
- driver-async/src/examples/primer/UpdatePrimer.java @ r2
- driver/build.gradle @ r2
- driver/src/examples/primer/AggregatePrimer.java @ r2
- driver/src/examples/primer/IndexesPrimer.java @ r2
- driver/src/examples/primer/InsertPrimer.java @ r3
- driver/src/examples/primer/PrimerTestCase.java @ r1
- driver/src/examples/primer/QueryPrimer.java @ r2
- driver/src/examples/primer/RemovePrimer.java @ r2
- driver/src/examples/primer/UpdatePrimer.java @ r2





---

<sup>**[bson/src/main/org/bson/Document.java, line 245 \[r5\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk3UZvsgcliEU6KKVtt)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/0e986687d526fd7ef27f2c8810110d015059627c/bson/src/main/org/bson/Document.java#L245)):</sup>
Let's do this, but also please add two more overloads that take a JsonWriterSettings instance, and have the default be new JsonWriterSettings()

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[bson/src/main/org/bson/Document.java, line 221 \[r5\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk3UZvsgcliEU6KKVtt)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/0e986687d526fd7ef27f2c8810110d015059627c/bson/src/main/org/bson/Document.java#L221)):</sup>
Done.

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69)







---

<sup>**[bson/src/main/org/bson/Document.java, line 235 \[r7\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/69#-Jk3iG9Riy8CT8sM7XWj)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/207cb43ae91b70597d982609e2536d6b4e334a64/bson/src/main/org/bson/Document.java#L235)):</sup>
Let's add an @throws CodecConfigurationException to all these methods to make it clear that they can fail.

---

**Comment by rozza** [comment]
Done and rebased.

**Pull request closed without merging**
