### PR TITLE
Added the Getting Started section to the documentation

### PR DESCRIPTION
**Pull request by rozza**
JAVA-1701

[Review on Reviewable](https://reviewable.io/reviews/rozza/mongo-java-driver/78)

### CODE REVIEW

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78)







---

<sup>**[docs/reference/content/getting-started/index.md, line 11 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQtZg5_siAbrPbs6IV)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/index.md#L11)):</sup>
Comma before follow

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 14 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQtk8tlWYEpScTUrsj)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L14)):</sup>
This 404s at 

   https://github.com/mongodb/mongo-java-driver/blob/master/src/driver/src/examples/tour/QuickTour.java

But we should link to the tag anyway, like:

  https://github.com/mongodb/mongo-java-driver/blob/r3.0.0-rc1/driver/src/examples/tour/QuickTour.java           

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 37 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQuPs0ugNvcefA3Tdn)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L37)):</sup>
Line up the first ServerAddress with the others

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 170 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQv4DXxzkrG-ih52s-)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L170)):</sup>
Maybe: call the first() method on the result of the find() of method  ?   It doesn't read well to  to mix method and operation like this

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 175 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQvH1KLg8eNC3ylLtz)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L175)):</sup>
Point out that first() will return null if no documents match (and not throw an exception)

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 187 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQvUsmv2uGOcmuFnPP)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L187)):</sup>
Let's use myDoc.toJson() instead of toString(). The output will look a lot better.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 201 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQvj8d2-8YWjaNLNxM)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L201)):</sup>
It actually returns a FindIterable.  If you don't want to say that, you can say "a subclass of Iterable that allows you to chain additional options to the query" or something like that.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 239 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQw6JLZAVttTEshJmW)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L239)):</sup>
toJson(), as above.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 281 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQwTtn4Oy3jlRRBqcZ)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L281)):</sup>
Rather than maxTime, let's add sort and projection examples instead.  It's so much more common.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 294 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQwiFCeOJWYJqNEz77)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L294)):</sup>
Let's remove the first sentence.  Most users won't know what the hell we're talking about (and rightly so).

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 305 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQwrTbeUsWfMnLE8YK)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L305)):</sup>
and reports all errors.  The use of aggregate may confuse people, thought I know what you mean

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 305 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQwzNnoqBUIZn_nZXR)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L305)):</sup>
I don't know if there is actually any parallelism.  If so, it's an implementation that is not specified.  So let's remove.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 339 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQxJ_sK61sbDzmBew3)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L339)):</sup>
How about:

Use of the bulkWrite methods is not recommended when connected to pre-2.6 MongoDB servers, as this was the first server version to support bulk write commands for insert, update, and delete in a way that allows the driver to implement the correct semantics for BulkWriteResult and BulkWriteException.  The methods will still work for pre-2.6 servers, but performance will suffer, as each write operation has to be executed one at a time.

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78)



---

First round of comments. Need to look at the admin guide still

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78)







---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 14 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQtk8tlWYEpScTUrsj)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L14)):</sup>
srcref is currently broken - will fix outside this review 

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78)







---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 292 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlR-0jdftLZ0AunlwzN)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L292)):</sup>
We need to also show updateOne/Many and deleteOne/Many, especially as we're showing bulk below that includes them

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78)







---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 37 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQuPs0ugNvcefA3Tdn)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L37)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 201 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQvj8d2-8YWjaNLNxM)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L201)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 239 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQw6JLZAVttTEshJmW)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L239)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 281 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQwTtn4Oy3jlRRBqcZ)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L281)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 292 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlR-0jdftLZ0AunlwzN)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L292)):</sup>
I'll add that to the ticket to add.  We currently dont have them in our quick tour and I'd like to crack on with the async version so we have something.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 305 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQwrTbeUsWfMnLE8YK)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L305)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 305 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQwzNnoqBUIZn_nZXR)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L305)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 339 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQxJ_sK61sbDzmBew3)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L339)):</sup>
Done.

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78)







---

<sup>**[docs/reference/content/getting-started/quick-tour.md, line 294 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlQwiFCeOJWYJqNEz77)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/quick-tour.md#L294)):</sup>
Done.

---

**Comment by jyemin** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78)







---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 15 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRDOJqaXGq7sCZnacP)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L15)):</sup>
"use the Java driver to execute basic CRUD operations"

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 63 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRELmAXCmwEhmKJVQH)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L63)):</sup>
creating an index will do it too.

This paragraph is awkwardly phrased though.  How about.

Collections in MongoDB are created automatically simply by inserted a document into it.  Using the createCollection method, you can also create a collection explicitly in order to to customize its configuration.  For example, to create a [capped collection](link to docs.mongodb.org) sized to 1 megabyte: 

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 68 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlREvY2tTSosfwpO68g)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L68)):</sup>
spurious \_, I think

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 93 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRFApG1Dge5H-TPI_w)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L93)):</sup>
This sentence can be removed

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 97 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRFRIVQXlmzc6DegpA)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L97)):</sup>
secondary indexes

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 97 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRFVI5-cBM1l4EOFTD)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L97)):</sup>
specify the field or combination of fields, and for each field specify the direction of the index for that field  

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 104 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRFNtNpPAgLitgBLam)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L104)):</sup>
removed leading space

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 110 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRFvo75Sk4Ty1yxBw3)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L110)):</sup>
The other examples don't mention the name of the collection, so not necessary here either

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 114 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRG1OrDXAgdsG_YlhN)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L114)):</sup>
Use toJson()

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 121 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRG39yNOVPOjY9PH8y)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L121)):</sup>
Replace with output of toJson()

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 134 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRGBMeHsCP6dyLWU04)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L134)):</sup>
Oops: Use Document not BasicDBObject

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 147 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRGevovzq3QNZxX31w)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L147)):</sup>
Use Filters.text method instead

---

**Comment by rozza** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78)







---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 15 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRDOJqaXGq7sCZnacP)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L15)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 63 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRELmAXCmwEhmKJVQH)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L63)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 68 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlREvY2tTSosfwpO68g)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L68)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 93 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRFApG1Dge5H-TPI_w)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L93)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 97 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRFRIVQXlmzc6DegpA)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L97)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 97 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRFVI5-cBM1l4EOFTD)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L97)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 104 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRFNtNpPAgLitgBLam)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L104)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 114 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRG1OrDXAgdsG_YlhN)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L114)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 121 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRG39yNOVPOjY9PH8y)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L121)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 134 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRGBMeHsCP6dyLWU04)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L134)):</sup>
Done.

---

<sup>**[docs/reference/content/getting-started/admin-quick-tour.md, line 147 \[r2\]](https://reviewable.io:443/reviews/rozza/mongo-java-driver/78#-JlRGevovzq3QNZxX31w)** ([raw file](https://github.com/rozza/mongo-java-driver/blob/272796b6ff43a66d249a6780029cf202e806f649/docs/reference/content/getting-started/admin-quick-tour.md#L147)):</sup>
Done.

---

**Comment by rozza** [comment]
I have merged the first lot into master, I will add the updateOne etc examples separately.

**Pull request closed without merging**
